name: mymemories
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  uuid: ^4.4.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  media_scanner: ^2.1.0
  photo_view: ^0.15.0
  carousel_slider: ^4.2.1
  flutter_speed_dial: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/dark_logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/dark_logo.png"
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/